-- Seed Rotary Stability exercises
DELETE FROM public.exercises_library WHERE pattern = 'rotary_stability';

INSERT INTO public.exercises_library (pattern, phase, posture_level, posture_name, name) VALUES
-- Level 1 Supine / Reset
('rotary_stability','Reset',1,'Supine','90/90 Breathing Position'),
('rotary_stability','Reset',1,'Supine','Foam Roller - Gluteal Muscle'),
('rotary_stability','Reset',1,'Supine','Foam Roller - Mid Back'),
('rotary_stability','Reset',1,'Supine','Get-up Roll to Press Arm-bar with One KB'),
('rotary_stability','Reset',1,'Supine','Get-Up to Elbow with Shoulder Rotations'),
('rotary_stability','Reset',1,'Supine','Get-up to Press'),
('rotary_stability','Reset',1,'Supine','Get-up to Tall Sit'),
('rotary_stability','Reset',1,'Supine','Leg Lowering Bridge with Disc Pillow and Foam Roller'),
('rotary_stability','Reset',1,'Supine','Leg Lowering with Disc Pillow and Glider'),
('rotary_stability','Reset',1,'Supine','Leg Lowering with Disc Pillow and Mini Band'),
('rotary_stability','Reset',1,'Supine','Rolling Lower Body'),
('rotary_stability','Reset',1,'Supine','Rolling Lower Body with Lower Body Feedback'),
('rotary_stability','Reset',1,'Supine','Rolling Lower Body with Upper Body Feedback'),
('rotary_stability','Reset',1,'Supine','Rolling Starfish Pattern One Supine to Prone with FMT'),
('rotary_stability','Reset',1,'Supine','Rolling Upper Body'),
('rotary_stability','Reset',1,'Supine','Single Arm Bench Press with DB'),
('rotary_stability','Reset',1,'Supine','Single Arm Bench Press with Hip Bridge'),
('rotary_stability','Reset',1,'Supine','Trunk Stability Rotation Knees Extended'),
('rotary_stability','Reset',1,'Supine','Trunk Stability Rotation Knees Flexed'),
-- Level 2 Prone / Reset
('rotary_stability','Reset',2,'Prone','Crocodile Breathing Partner Assist'),
('rotary_stability','Reset',2,'Prone','Crocodile Breathing with Ankle Weights'),
('rotary_stability','Reset',2,'Prone','Full Bow Stretch'),
('rotary_stability','Reset',2,'Prone','Prone T-Spine Rotation'),
('rotary_stability','Reset',2,'Prone','Rolling Starfish Pattern Two Prone to Supine with FMT'),
-- Level 3 Side Lying / Reset
('rotary_stability','Reset',3,'Side Lying','Get-up Press to Elbow Thoracic Waves with KB'),
-- Level 4 Quadruped / Reactivate
('rotary_stability','Reactivate',4,'Quadruped','Assisted Bird Dog - Leg slide with opposite arm lift'),
('rotary_stability','Reactivate',4,'Quadruped','Quadruped Diagonals with Neutral Spine'),
('rotary_stability','Reactivate',4,'Quadruped','Quadruped Reach with Neutral Spine'),
('rotary_stability','Reactivate',4,'Quadruped','Quadruped Rock with Core Activation'),
('rotary_stability','Reactivate',4,'Quadruped','Resisted Quadruped Leg Extension with FMT'),
-- Level 6 Tall Kneeling / Reactivate
('rotary_stability','Reactivate',6,'Tall Kneeling','D1 Extension from Tall Kneeling with Cable System'),
('rotary_stability','Reactivate',6,'Tall Kneeling','D2 Extension from Tall Kneeling with Cable System'),
('rotary_stability','Reactivate',6,'Tall Kneeling','D2 Flexion from Tall Kneeling with Cable System'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Pull Single Arm from Tall Kneeling with Cable System'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Push Single Arm from Tall Kneeling with Cable System'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Single Arm Tall Kneeling Overhead Cable Press'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Bicep Curl'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Chop with FMT'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Curl to Press'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling DB Military Press'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling KB Halo'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling KB Press'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Single Arm Bicep Curl'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Single Arm Curl to Press'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Single Arm Overhead Press'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Single Arm Press with DB'),
('rotary_stability','Reactivate',6,'Tall Kneeling','Tall Kneeling Turns Symmetrical Load'),
-- Level 7 Half Kneeling / Reactivate
('rotary_stability','Reactivate',7,'Half Kneeling','Chop from Half Kneeling with Cable Bar'),
('rotary_stability','Reactivate',7,'Half Kneeling','D1 Extension from Half Kneeling with FMT'),
('rotary_stability','Reactivate',7,'Half Kneeling','D1 Flexion from Half Kneeling with FMT'),
('rotary_stability','Reactivate',7,'Half Kneeling','Get-up Half Kneeling to Stand Split Stance Bottoms Up Press with One KB'),
('rotary_stability','Reactivate',7,'Half Kneeling','Half Kneeling Bicep Curl'),
('rotary_stability','Reactivate',7,'Half Kneeling','Half Kneeling KB Press'),
('rotary_stability','Reactivate',7,'Half Kneeling','Half Kneeling Lift with Cable Bar'),
('rotary_stability','Reactivate',7,'Half Kneeling','Half Kneeling Lift with FMT'),
('rotary_stability','Reactivate',7,'Half Kneeling','Half Kneeling Rotation with Dowel'),
('rotary_stability','Reactivate',7,'Half Kneeling','Half Kneeling Set-Up'),
('rotary_stability','Reactivate',7,'Half Kneeling','Half Kneeling Single Arm Curl to Press'),
-- Level 8 Open Half Kneeling / Reactivate
('rotary_stability','Reactivate',8,'Open Half Kneeling','Get-up High Pelvis to Bend with KB'),
-- Level 9 Split Stance / Reinforce
('rotary_stability','Reinforce',9,'Split Stance','Bicep Curl from Split Stance with DB'),
('rotary_stability','Reinforce',9,'Split Stance','D1 Flexion from Split Stance with Cable System'),
('rotary_stability','Reinforce',9,'Split Stance','D2 Extension from Split Stance with Cable System'),
('rotary_stability','Reinforce',9,'Split Stance','D2 Flexion from Split Stance with Cable System'),
('rotary_stability','Reinforce',9,'Split Stance','Lunge Forward Double Arm Up with Cable Bar'),
('rotary_stability','Reinforce',9,'Split Stance','Lunge Forward Double Arm Up with Two DB'),
('rotary_stability','Reinforce',9,'Split Stance','Lunge Forward Resisted with Cable Bar'),
('rotary_stability','Reinforce',9,'Split Stance','Lunge Forward Single Arm Up with One DB'),
('rotary_stability','Reinforce',9,'Split Stance','Lunge Forward with Lateral Shift with Cable Bar'),
('rotary_stability','Reinforce',9,'Split Stance','Single Arm Split Stance Overhead Cable Press'),
('rotary_stability','Reinforce',9,'Split Stance','Split Squat Double Arm Down with Two KB'),
('rotary_stability','Reinforce',9,'Split Stance','Split Squat Goblet with One KB'),
('rotary_stability','Reinforce',9,'Split Stance','Split Squat Single Arm Up with One DB'),
('rotary_stability','Reinforce',9,'Split Stance','Split Squat Single Arm Up with One KB'),
('rotary_stability','Reinforce',9,'Split Stance','Split Stance KB Press'),
('rotary_stability','Reinforce',9,'Split Stance','Split Stance Lift with Cable Bar'),
('rotary_stability','Reinforce',9,'Split Stance','Split Stance Single Arm Bicep Curl'),
('rotary_stability','Reinforce',9,'Split Stance','Split Stance Single Arm Curl to Press'),
-- Level 10 Single Leg Supported / Reinforce
('rotary_stability','Reinforce',10,'Single Leg Supported','Push Single Arm from Single Leg Supported with Cable System'),
('rotary_stability','Reinforce',10,'Single Leg Supported','Row Single Arm from Single Leg Supported with Cable System'),
('rotary_stability','Reinforce',10,'Single Leg Supported','Single Leg Single Arm Supported Curl to Press'),
('rotary_stability','Reinforce',10,'Single Leg Supported','Single Leg Supported KB Press'),
('rotary_stability','Reinforce',10,'Single Leg Supported','Single Leg Supported Single Arm Bicep Curl'),
-- Level 11 Single Leg / Reinforce
('rotary_stability','Reinforce',11,'Single Leg','Push Single Arm from Single Leg with Cable System'),
('rotary_stability','Reinforce',11,'Single Leg','Single Leg DB Curl to Press'),
('rotary_stability','Reinforce',11,'Single Leg','Single Leg KB Press'),
('rotary_stability','Reinforce',11,'Single Leg','Single Leg Single Arm Bicep Curl'),
('rotary_stability','Reinforce',11,'Single Leg','Single Leg Single Arm Press'),
('rotary_stability','Reinforce',11,'Single Leg','Single Leg Supported Overhead Cable Press'),
('rotary_stability','Reinforce',11,'Single Leg','Step Up Double Arm Overhead with Two DB'),
-- Level 12 Standing / Reinforce
('rotary_stability','Reinforce',12,'Standing','KB Push Press'),
('rotary_stability','Reinforce',12,'Standing','Marching Double Arm down with Two DB'),
('rotary_stability','Reinforce',12,'Standing','Single Arm Bicep Curl'),
('rotary_stability','Reinforce',12,'Standing','Single Arm KB Push Press'),
('rotary_stability','Reinforce',12,'Standing','Step Up Double Arm Overhead with Two KB'),
('rotary_stability','Reinforce',12,'Standing','Step up Single Arm Down with One KB'),
('rotary_stability','Reinforce',12,'Standing','Step Up Single Arm Up with One KB'),
('rotary_stability','Reinforce',12,'Standing','Step-up Valgus Correction with FMT');